- name: Run backend
  community.docker.docker_container:
    name: backend
    image: slifos/tp-docker-simpleapi
    pull: true
    restart_policy: always
    networks:
      - name: app-network
    env:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/db
      SPRING_DATASOURCE_USERNAME: usr
      SPRING_DATASOURCE_PASSWORD: pwd
  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python
