  deploy:
    needs: build-and-push-docker-image
    runs-on: ubuntu-24.04
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Ansible
        run: pip install ansible

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan simon.jennequin-charles.takima.school >> ~/.ssh/known_hosts

      - name: Deploy with Ansible
        working-directory: ansible
        run: ansible-playbook -i inventories/setup.yml playbook.yml
